
- name: Ensure redis data/conf/log directories exist
  become: true
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - "{{ docker_redis_data_dir }}"
    - "{{ docker_redis_conf_dir }}"
    - "{{ docker_redis_log_dir }}"
  tags:
    - install
    - upgrade

- name: Configure redis
  template: src=redis.conf.j2 dest={{ docker_redis_conf }} mode='0644'

- name: Run docker redis container
  become: true
  docker:
    docker_api_version: "{{ docker_api_version }}"
    env: "{{ docker_redis_env }}"
    name: "{{ docker_redis_name }}"
    image: "{{ docker_redis_image }}"
    command: "{{ docker_redis_command }}"
    volumes: "{{ docker_redis_volumes }}"
    ports: "{{ docker_redis_ports }}"
    expose: "{{ docker_redis_expose }}"
    restart_policy: "always"
    state: "reloaded"
    volumes: "{{ docker_redis_volumes }}"
  tags:
    - install
    - upgrade

